# Generated by Django 3.0.4 on 2021-09-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='zip',
            field=models.FileField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
